#!/usr/local/bin/zsh

#
# Run kubectl commands, GKE requires gcloud for helpers
#
function gcloud() {

if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

#if [[ -z "$K8S_VERSION" ]]; then
#  K8S_VERSION="1.14"
#fi

docker run --name "$DOCKER_RAND_ID" --rm -ti \
  -v $(pwd):$(pwd) \
  -w $(pwd) \
  -v $HOME/.config/gcloud:/root/.config/gcloud \
  google/cloud-sdk:latest gcloud $kns $argv[*]
}