#!/usr/local/bin/zsh

#
# Run gsutil commands
#
function gsutil() {

if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

docker run --name "$DOCKER_RAND_ID" --rm -ti \
  -u 1000:1000 \
  -w $(pwd) \
  -v $(pwd):$(pwd) \
  -v "$HOME"/.config/gcloud:/home/clitools/.config/gcloud \
  docker.pkg.github.com/bulderbank/cloud-cli-tools/cli-tools:latest gsutil $argv
}