#!/usr/local/bin/zsh
# Run helm v3 commands with docker
function helm() {
if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi
docker run --name "$DOCKER_RAND_ID" --rm -ti \
  -e KUBE_EDITOR=vim \
  -v $(pwd):$(pwd) \
  -w $(pwd) \
  -v $HOME/.helm/repository:/root/.helm/repository:cached \
  -v $HOME/.helm/cache:/root/.cache/helm:cached \
  -v $HOME/.helm/config:/root/.config/helm:cached \
  -v $HOME/.helm/data:/root/.local/share/helm:cached \
  -v $HOME/.kube/config:/root/.kube/config:cached \
  -v $HOME/.config/gcloud:/root/.config/gcloud:cached \
  frealmyr/gke-helm:v3.2.4 $argv
}
