#!/usr/local/bin/zsh

# Run helm commands with docker

function helm2() {

if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

docker run --name "$DOCKER_RAND_ID" --rm -ti \
  -v $(pwd):$(pwd) \
  -w $(pwd) \
  -v $HOME/.kube/config:/root/.kube/config \
  -v $HOME/.config/gcloud:/root/.config/gcloud \
  -v $HOME/.helm:/root/.helm \
  jonasberdal/gke-helm:v2.16.8 $argv
}