#!/usr/local/bin/zsh
#
# Run kubectl commands, GKE requires gcloud for helpers
#

function jq() {
if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

docker run --name "$DOCKER_RAND_ID" --rm -ti \
  stedolan/jq $argv[*]
}