#!/usr/local/bin/zsh

#
# Get the active kubectl context
#
function kcc() {

if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

docker run --name "$DOCKER_RAND_ID" --rm -ti \
  -u 1000:1000 \
  -v $HOME/.kube/config:/home/clitools/.kube/config \
  docker.pkg.github.com/bulderbank/cloud-cli-tools/cli-tools:latest kubectl config current-context
}