#!/usr/local/bin/zsh

#
# Set the default namespace
#
function knsd() {
: ${1?"knsd DEFAULT_NAMESPACE"}

if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

docker run --name "$DOCKER_RAND_ID" --rm -ti \
  -u 1000:1000 \
  -v $HOME/.kube:/home/clitools/.kube \
  docker.pkg.github.com/bulderbank/cloud-cli-tools/cli-tools:latest kubectl config set-context --current --namespace=$argv[1]
}