#!/usr/local/bin/zsh
#
# Get the active kubectl context
#
function kubectl() {
if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi
if [[ -z "$K8S_VERSION" ]]; then
  K8S_VERSION="1.16"
fi
docker run --name "$DOCKER_RAND_ID" --rm -ti \
  -v $HOME/.kube/:/.kube/ \
  bitnami/kubectl:$K8S_VERSION $kns $argv[*]
}