#!/usr/local/bin/zsh

#
# Run Terraform plan
#
function tfplan() {

if [[ -n $(echo *.tf) ]]
then
  tf plan -parallelism=25 $(for filename in env/$ENVIRONMENT/*.tfvars; do printf "%s%s " "-var-file=" "$filename" ; done)
else
  echo "There are no Terraform files in this folder, aborting.."
fi

}