#!/usr/local/bin/zsh

#
# Rename the active kubectl context
#
function kcrename() {
: ${1?"kcrename new_context_name"}

if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

if [[ -z "$K8S_VERSION" ]]; then
  K8S_VERSION="1.14"
fi

docker run --name "$DOCKER_RAND_ID" --rm -ti \
  -v $HOME/.kube/:/.kube/ \
  bitnami/kubectl:$K8S_VERSION config rename-context $(kcecho config current-context | tr -d '\r') $argv[1]
}