#!/usr/local/bin/zsh

#
# Set the default namespace
#
function knsd() {
: ${1?"knsd DEFAULT_NAMESPACE"}

if [[ -z "$DOCKER_RAND_ID" ]]; then
  DOCKER_RAND_ID=$RANDOM
fi

if [[ -z "$K8S_VERSION" ]]; then
  K8S_VERSION="1.14"
fi

docker run --name "$DOCKER_RAND_ID" --rm -ti \
  -v $HOME/.kube/:/.kube/ \
  bitnami/kubectl:$K8S_VERSION config set-context --current --namespace=$argv[1]
}