#!/usr/local/bin/zsh

source ~/.dotfiles/funcs/pdfcracker
source ~/.dotfiles/funcs/gbclean
source ~/.dotfiles/funcs/gcb
source ~/.dotfiles/funcs/helm
source ~/.dotfiles/funcs/helm-unittest
source ~/.dotfiles/funcs/k
source ~/.dotfiles/funcs/kcecho
source ~/.dotfiles/funcs/kcrename
source ~/.dotfiles/funcs/kns
source ~/.dotfiles/funcs/knsd
source ~/.dotfiles/funcs/kset
source ~/.dotfiles/funcs/terraform

function print_dotfiles() {
    echo "\n#########################################################################"
    echo "zshrc: "
    echo "#########################################################################\n"
    cat ~/.zshrc
    echo "\n#########################################################################"
    echo "Aliases: "
    echo "#########################################################################\n"
    cat ~/.dotfiles/.aliases
    echo "\n#########################################################################"
    echo "Functions: "
    echo "#########################################################################\n"
    cat ~/.dotfiles/.functions
}

function mkcd() {
    mkdir -p "$@" && cd "$_";
}

functions sync_dotfiles() {
    rsync -r --exclude '.git/' ~/Code/dotfiles/ ~ && source ~/.zshrc 
}
